image: "python:3.9.5"

before_script:
  - cp backend/src/backend/backend_proxy/config_example.py backend/src/backend/backend_proxy/config.py # credentials are not important
  - pip install -r backend/requirements.txt
  - pip install -e backend
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | base64 -d |  tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


stages:
  - test
  - deploy

unit_test:
  stage: test
  script:
  - pytest -p no:cacheprovider backend/

deployProd:
    stage: deploy
    script:
    - ssh dip@nlp.cmpe.boun.edu.tr "cd nlp-tools-platform && git pull && docker-compose up --build -d && exit"
    when: manual
