version: '3'
services:
  system-health:
    build: 
      context: .
    container_name: system-health
    hostname: system-health
    ports:
      - "5001:5000"
    networks:
      - DIP-network
    
networks:
  DIP-network:
      external: true